### ISSUE TITLE
[FE/BE] 코드 설정 일괄 변경

### ISSUE THREAD

**Issue by nobel6018** [penguinsAtEgloo/E-Gloo#141]
1. CRLF와 LF 혼용 --> LF로 일괄 변경
    - .gitattributes 파일 추가
    - git 설정 변경 (선택적)
    - 참고: [git-crlf](https://www.lesstif.com/gitbook/git-crlf-20776404.html#git%EC%97%90%EC%84%9CCRLF%EA%B0%9C%ED%96%89%E[…]ED%95%98%EA%B8%B0-%ED%95%B4%EA%B2%B0%EC%B1%85)
2. 불필요한 디렉토리, 파일 삭제
    - back-end-api/logs 삭제
    - jwt-auth-api 디렉토리 삭제

**Comment by upswp** [comment]
서버측에서 log 체크하고 로컬쪽에 쌓이는 로그는 삭제해도 좋다고 봅니다 👍🏻
