### ISSUE TITLE
[BE] ERD 1차안 작성

### ISSUE THREAD

**Issue by upswp** [penguinsAtEgloo/E-Gloo#16]
- Null 값 여부 설정
- 타입 설정
- UNIQUE 여부 설정
- Validation 여부 설정
- 관계도 설정
  - 레시피 직접 생성한다는 가정하에 작성 진행

**Comment by haewoniee** [comment]
이거 완료된거에요?

**Comment by dongyeon94** [comment]
아직 진행중입니다.

**Comment by upswp** [comment]
> 이거 완료된거에요?

진행중입니다 오늘중에 완료됩니다
